import{a as q,S as v,i as s}from"./assets/vendor-CNqCr-V-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const P="53458561-7a242f881cc334c9983cae72b",R="https://pixabay.com/api/",B=15;async function m(o,t=1){try{return(await q.get(R,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:B,page:t}})).data}catch(i){throw console.error("Error fetching images:",i),i}}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".load-more"),$=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:i,largeImageURL:l,tags:e,likes:r,views:n,comments:E,downloads:S})=>`
      <li class="gallery-item">
        <a href="${l}">
          <img src="${i}" alt="${e}" />
        </a>
        <ul class="info">
          <li><b>Likes:</b> ${r}</li>
          <li><b>Views:</b> ${n}</li>
          <li><b>Comments:</b> ${E}</li>
          <li><b>Downloads:</b> ${S}</li>
        </ul>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function M(){f.innerHTML=""}function b(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function O(){p.classList.remove("hidden")}function h(){p.classList.add("hidden")}const w=document.querySelector(".form"),x=w.querySelector('input[name="search-text"]'),A=document.querySelector(".load-more");let c="",u=1,d=0,a=0;w.addEventListener("submit",async o=>{if(o.preventDefault(),c=x.value.trim(),!c){s.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}u=1,a=0,d=0,M(),h(),b();try{const t=await m(c,u);if(d=t.totalHits,!t.hits.length){s.warning({title:"No results",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}y(t.hits),a+=t.hits.length,a>=d?(h(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):O()}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}});A.addEventListener("click",async()=>{u+=1,b();try{const o=await m(c,u);y(o.hits),a+=o.hits.length,(a>=d||o.hits.length<15)&&(h(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{s.error({title:"Error",message:"Unable to load more images.",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
